TexFile = Dir["*.tex"].first
BaseName = File.basename(TexFile, ".tex")
DviTarget = BaseName + ".dvi"
PSTarget = BaseName + ".ps"
PDFTarget = BaseName + ".pdf"
BibFile = Dir["*.bib"].first
if BibFile
  BibBase = File.basename(BibFile, ".bib")
end

def bibtex
  aux = Dir["*.aux"].first
  sh "bibtex #{File.basename(aux, '.aux')}"
end

file DviTarget => [TexFile, BibFile] do
  sh "latex #{TexFile}"
  bibtex()
  sh "latex #{TexFile}"  
  sh "latex #{TexFile}"
end

task :deploy => :pdf do
  sh "cp #{PDFTarget} /Users/feldt/feldt/general/web/advice"
end

task :letter_ps => DviTarget do
  sh "dvips -t letter -o #{PSTarget} #{DviTarget}"
end

task :letter_pdf_via_ps => :letter_ps do
  sh "ps2pdf -dPDFSETTINGS=/prepress #{PSTarget}"
end

task :a4_pdf_via_ps => DviTarget do
  sh "dvips -t a4 -o #{PSTarget} #{DviTarget}"
  sh "ps2pdf -dPDFSETTINGS=/prepress #{PSTarget}"  
end

if BibFile
  pdfdeps = [TexFile, BibFile]
else
  pdfdeps = [TexFile]
end

task :pdf => pdfdeps do
  sh "pdflatex #{TexFile}"
  bibtex()
  sh "pdflatex #{TexFile}"  
  sh "pdflatex #{TexFile}"
  #stamp = Time.now.strftime("%y%m%d_%H%M%S")
  #sh "mv #{PDFTarget} #{BaseName}_version_#{stamp}.pdf"
end

task :default => :pdf

task :clobber => :clean do
  sh "rm -rf #{PSTarget} #{PDFTarget} #{BaseName}_version_*.pdf"
end

task :clean do
  sh "rm -rf *.aux *.bbl *.blg *.dvi *.log *.out"
end
